name: azure-ducklake-quack
metadata:
  template: azd-init

infra:
  provider: bicep
  path: infra

services:
  gateway:
    project: .
    host: containerapp
    image: azdq-gateway
    docker:
      path: docker/gateway.Dockerfile
      context: .
  reader:
    project: .
    host: containerapp
    image: azdq-runtime
    docker:
      path: docker/runtime.Dockerfile
      context: .
  writer:
    project: .
    host: containerapp
    image: azdq-runtime
    docker:
      path: docker/runtime.Dockerfile
      context: .

