[package]
name = "azdq-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
azdq-policy = { path = "../policy" }
duckdb.workspace = true
native-tls.workspace = true
postgres-native-tls.workspace = true
serde.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
